version: '3.6'
services:
  web:
    image: odoo:17.0
    container_name: ddev-${DDEV_SITENAME}-web
    restart: unless-stopped
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=postgres
      - PASSWORD=postgres
    volumes:
      - ../extra-addons:/mnt/extra-addons
      - ../config/odoo.conf:/etc/odoo/odoo.conf
    depends_on:
      - db

