services:
  odoo:
    image: odoo:17.0
    container_name: ddev-${DDEV_SITENAME}-odoo
    restart: unless-stopped
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=db
      - PASSWORD=db
    volumes:
      - ../extra-addons:/mnt/extra-addons
      - ../config/odoo.conf:/etc/odoo/odoo.conf
    depends_on:
      - db
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
